-- LibCS entry point file
-- The main addon is now created in core/Core.lua
-- This file provides type definitions and serves as the entry point
---@class LibCS : AceAddon, AceConsole-3.0, AceEvent-3.0
---@field CharacterFrameBg Frame
---@field CharacterFrameBgTex Texture
---@class LibCS.DB
---@field enabled boolean
---@field offset number
---@field background LibCS.DB.Background
---@field padding LibCS.DB.Padding
---@field scale number
---@field debug boolean
---@field modules LibCS.DB.Modules
---@class LibCS.DB.Background
---@field DynamicImage boolean
---@field image string
---@field color number[]
---@field border LibCS.DB.Border
---@class LibCS.DB.Border
---@field enabled boolean
---@field alpha number
---@field scale number
---@class LibCS.DB.Padding
---@field h number
---@field v number
---@class LibCS.DB.Modules
---@field portrait table
---@field equipment table
---@field addonintegration table
---@field reputation table
---@field enhancedequipment table
---@field lootspec table
---@field modelcontrols table
---@field notifications table
---@class LibCS.Lib
---@field AceDB AceDB-3.0
---@field AceConfig AceConfig-3.0
---@field AceConfigDialog AceConfigDialog-3.0
-- All functionality is now in core/Core.lua
-- This file only provides type definitions for LuaLS
